name: CI/CD - Build & Deploy

on:
  push:
    branches: [ "main" ]  # Chạy khi push lên nhánh main

jobs:
  build-and-push:
    name: Build Docker Image & Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Bước 1 - Tải code về
        uses: actions/checkout@v4

      - name: Bước 2 - Đăng nhập DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Bước 3 - Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nguyenanhphu/nguyenanhphu:latest

      - name: Bước 4 - Trigger Deploy qua Webhook
        run: |
          curl -X POST ${{ secrets.DEPLOY_URL }}
